### ISSUE TITLE
Control indexer revision_id to avoid ES failure

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-indexer#100]
When indexing the revision_id of the record is sent directly:

```python
return self.client.index(
        id=str(record.id),
        version=record.revision_id,
        version_type=self._version_type,
        index=index,
        doc_type=doc_type,
        body=self._prepare_record(record, index, doc_type),
)
```

It is true that Elasticsearch will crosscheck that, but in case an update arrives out of order or it is somehow tampered (e.g. signals) it will throw an exception.

Would it be good to add a check and avoid the indexing error. Maybe even potentially rollingback the DB commit in ``invenio-records-rest`` to avoid an inconsistent state?

This last question might apply not only to this but in general, to check the indexing result and rollback if needed (although this should be on ``invenio-records-rest``).

**Comment by ppanero** [comment]
@lnielsen I think this is fixed by UoW + service components, re-open if not (It was opened due to some errors found when processing full-text extraction in CERN search)

**Comment by zyzzyxdonta** [comment]
Hi,

I think we ran into this. See the error message attached. Which package(s) would we need to upgrade in order to fix this?

We're currently using

```
invenio-indexer==1.1.0
invenio-records-rest==1.6.2
elasticsearch==7.0.5
elasticsearch-dsl==7.0.0
```

[invenio-indexer.txt](https://github.com/inveniosoftware/invenio-indexer/files/9783139/invenio-indexer.txt)

Thanks in advance!

**Comment by ppanero** [comment]
@zyzzyxdonta in `invenio-records-rest` this is probably still happening. However, it was fixed in the new implementation (`invenio-records-resources`) that is being used in InvenioRDM

**Comment by zyzzyxdonta** [comment]
So there's no way of fixing this on our current setup before switching to RDM?

I'd be happy to fork a repo or two and change some code if you could give me some hints.

**Comment by ppanero** [comment]
@zyzzyxdonta IIRC, the issue was fixed by applying the Unit of Work pattern in the business logic. i.e. encapsulating the actions that take place before commiting an object. The core of it happens [here](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/uow.py), which then is used as a decorator. However, it's implementation is heavily based on how it is used in the "resources" world (i.e. RDM). I'm unsure how much work/feasible would it be to implement it in the "*-rest" world.

**Comment by zyzzyxdonta** [comment]
Thank you so much! I'll have a look and then decide with my colleagues if it's worth it.
