### ISSUE TITLE
invenio-search dependency

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-indexer#109]
I got this error:
```
    from invenio_search.utils import build_alias_name
ImportError: cannot import name 'build_alias_name'
meleze ~/devel/rero/rero-ils on maj-cataloging-#928(v
```

The problem is since the version 1.1.0 it use `build_alias_name` which is available only in `invenio-search>=1.2.0`. Some new contraints should be added in the `setup.py`.

**Comment by slint** [comment]
This is actually done: https://github.com/inveniosoftware/invenio-indexer/blob/16e6b1e23e005f762b3e926a39f3714c9bf5e5e9/setup.py#L32.

Do you still have issues with that?

**Comment by jma** [comment]
I should be ok. I got this problem with the 1.1.0 version of invenio-indexer.
