### ISSUE TITLE
api: reindex doesn't work if the queue is not initialized

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-indexer#11]
**Problem**:
If, after install invenio3, I run:
```
invenio3 index reindex --yes-i-know
invenio3 index run
```
It doesn't index the records because the queue is not previously declared.
What we need to do is [declare the queue](https://github.com/inveniosoftware/invenio-indexer/blob/master/tests/conftest.py#L96-L101) the first time we initialize the system.

**Solution proposed**:
We can add a signal inside the `invenio-search` cli `init` and `destroy`; in the same time, in `invenio-indexer` register a signal to `initialize` and `destroy` the queue every time the indices are created or destroyed.

----------------------------------------------------------------------
cc @lnielsen @jirikuncar

**Comment by jirikuncar** [comment]
IMHO `reindex` could create and purge the queue.

**Comment by lnielsen** [comment]
Declaring the queue is comparable to creating indexes in ES or tables in the DB, so I don't think ``reindex`` would be the right place.

**Comment by jirikuncar** [comment]
@lnielsen I am fine with adding new signals. There should be another way to create/purge the queue without creating/dropping all indices.

**Comment by jirikuncar** [comment]
**Proposal**

- `invenio3 index queue init`
- `invenio3 index queue purge`
- `invenio3 index queue destroy`
