### ISSUE TITLE
api: impossibility to use multiple custom elasticsearch indexes

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-indexer#30]
**Problem:**
The only way to index records in multiple custom indexes (not depending on the JSON-Schema URI) is to create a custom `RecordIndexer` and give it a custom  `record_to_index` function.

The CLI and tasks recreate the `RecordIndexer` instances at each call. Thus they will always use the default `record_to_index`. Thus it is not possible to create custom `RecordIndexer` as the CLI would behave differently.

**Possible Solutions:**
1/ Have only one `RecordIndexer`.
- Add a config variable which can point to an alternative `RecordIndexer` class. The CLI should use it.
- Make the indexing methods class methods.
- Remove customization arguments from the constructor and add them as class attributes.

Effect on other projects:
- invenio-deposit: need to remove [the creation of a `RecordIndexer`](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L115)

2/ Allow multiple `RecordIndexer`.
- Register a dict of `RecordIndexer` on the InvenioIndexer extension.
- Add a parameter to the CLI which enables to choose which `RecordIndexer` should be used.

Problem: How do we know which record should be indexed with which `RecordIndexer`?

3/ Remove the CLI

Problem: the database and the elasticsearch index will eventually stop being consistent (one server crash is enough).  Thus being able to reindex everything is mandatory.

**Comment by nharraud** [comment]
cc @inveniosoftware/triagers

**Comment by jirikuncar** [comment]
@nharraud Invenio-Indexer is an opinionated package on how the indexing should be done. It might be easier to create `b2share-indexer` with your specific workflow.

We can make the indexer class configurable in Invenio-Deposit package.

**Comment by nharraud** [comment]
After some more musing, we could use different JSON-Schema references for our records, at least for partial metadata save.

However we still have a problem: our references are JSON-Pointers and the current [`invenio_search.utils.schema_to_index`](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/utils.py#L32) function used by [`_record_to_index` function](https://github.com/inveniosoftware/invenio-indexer/blob/fd19168985d21c896d88684fd08798704b6b560b/invenio_indexer/api.py#L46) is not able to handle JSON-pointers.

We could try to make `invenio_search.utils.schema_to_index` or `_record_to_index` more generic, or we could make one of these functions configurable with a config variable. This would not resolve the "CLI with default RecordIndexer" issue discribed above but it would at least enable to control in what indices the records are sent to.

**Example of JSON-pointers:**
This is one of our community schema which should validate records sent to this community.
GET `/api/communities/<ID>/schemas/<version_nb>`
=> `{ 'version_nb': <version_nb>, 'released': <date>, 'json_schema': {...} }`

This schema is then referenced in records with JSON-Pointers.
`{ '$schema': '/api/communities/<ID>/schemas/<version_nb>#/json-schema'}`

**Comment by lnielsen** [comment]
What about creating a proxy ``current_indexer``, which is an instance of ``RecordIndexer`` that is initialised with custom ``record_to_index`` function?

**Comment by jirikuncar** [comment]
Alternatively, we can add property on `current_search.schema_to_index` as it is being used in several places. WDYT?

**Comment by nharraud** [comment]
@lnielsen @jirikuncar So it would be done the same way [as for `invenio-records-rest`'s state class](https://github.com/inveniosoftware/invenio-records-rest/blob/3ceb80bb39062b2b01d49f569e02413a4d70951b/invenio_records_rest/ext.py#L47)? With the state class reading a config variable? This would work for me.

@jirikuncar Providing `current_search.schema_to_index` would also be enough for me. I just wonder if other people might want to define their indexes on something else than the JSON-Schema url.

I might have missed some modules but I didn't find any other place than invenio-indexer where `schema_to_index` is used. I thought that invenio-search would use it too but in fact it is only referencing it in tests. Are there other modules I missed?

**Comment by jirikuncar** [comment]
> I didn't find any other place than invenio-indexer where `schema_to_index` is used

Invenio-ORCID (https://github.com/search?q=org%3Ainveniosoftware+schema_to_index&type=Code)

**Comment by nharraud** [comment]
@jirikuncar Thanks for the link. I indeed missed that one.

I see that the invenio-ORCID also has the record when they ask for the index. Why not have a `record_to_index` there too?
Are there use cases where we have only the json-schema (no record) and need the index to which it is mapped, or do we always ask the index once we have a record?

As I said before having `current_search.schema_to_index` is enough for me. I am just wondering if we need to tie the indexes to the JSON-Schema. It could just be the default implementation.

**Comment by nharraud** [comment]
I'll make a PR with the implementation Lars suggested, i.e. 
> What about creating a proxy current_indexer, which is an instance of RecordIndexer that is initialised with custom record_to_index function?

It's still the most flexible approach and avoid adding further config variables if/when the indexer becomes more complex and has more parameters.

**Comment by lnielsen** [comment]
Already done since we had other issues with conflicting doc_type being generated: https://github.com/inveniosoftware/invenio-indexer/commit/0dce9c471dde7830cbcab15ee2b6356039f80e0e

**Comment by nharraud** [comment]
@lnielsen perfect thanks !
