### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-indexer#31]
- [x] check existing API functionality
  - [ ] api: check signature of Publisher.publish or add data validation #4
  - [x] api: impossibility to use multiple custom elasticsearch indexes #30
- [x] add missing important API functionality
- [x] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by hachreak** [comment]
@jirikuncar @lnielsen do you think the first 3 points are fine? Or do we need to improve somehow the API?

**Comment by jirikuncar** [comment]
@hachreak we should check with @nharraud because of #30.
