### ISSUE TITLE
Implement full-text indexing for attached documents

### ISSUE THREAD

**Issue by zazasa** [inveniosoftware/invenio-indexer#46]
# Full-text indexing with the ES Mapper Attachments Plugin

I propose to use this plugin to implement the indexing of attached documents:
[Mapper Attachments Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/2.4/mapper-attachments.html)

It is a fast and easy solution, maintened by the Elasticsearch team.
As described in the link above, it uses the Tika library to analyze the content of a file.
## A first example

The Mapper attachment plugin for elasticsearch provides you a new field type named attachment. In order to use it you first need to setup your mapping. Here for instance i create a tind-doc index, with a tind_document type, with 3 properties [filename, insert_date, file]. The file properties has the type attachment with his configuration:

``` json
PUT tind-doc/
{
    "mappings": {
      "tind_document": {
        "_source":{
          "excludes":["file"]
        },
        "properties": {
          "file": {
            "type": "attachment",
            "fields": {
              "content": {
                "type": "string",
                "term_vector": "with_positions_offsets",
                "store":"yes"
              },
              "author": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "date": {
                "type": "date",
                "format": "strict_date_optional_time||epoch_millis"
              },
              "keywords": {
                "type": "string"
              },
              "content_type": {
                "type": "string"
              },
              "content_length": {
                "type": "integer"
              },
              "language": {
                "type": "string",
                "store":"yes"
              }
            }
          },
          "filename": {
            "type": "string"
          },
          "insert_date": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          }
        }
      }
    }
}
```

Once you defined the  `"type":"attachment"` there are several field provide automatically by the Tika parser that could be set up with a proper mapping customization.  (by default the language recognition is disabled, look at the link to enable it).
Anyway i found that most of this field , in our case, are not properly recognited, and we can get rid of them.

The most important is the **content** field that is where our file will be inserted, the `"term_vector"` option is required for the highlights feature that will be showed later.
## Index a document

For indexing a document ES require a base64 encoded string. Below i show a working script for encode the document and put it into ES.

``` python
class TindDocument(DocType):
    filename = String()
    insert_date = Date()
    file = Attachment(fields={
        'content': String(term_vector="with_positions_offsets", store=True),
    })

    class Meta:
        index = 'tind-doc'

connections.create_connection(hosts=['localhost'])

for input_file in doc_files:
    with open(input_file, "rb") as ifd:
        b = base64.b64encode(ifd.read())

    attachment = dict(
        _content=b,
        _indexed_chars=-1,
        _detect_language=True,
    )

    firstdoc = TindDocument(
        filename=input_file, insert_date=datetime.now(), file=attachment)
    firstdoc.save()
```

There are some options that you can provide. 
- The `_detect_language` if you want to say ES to try to detect the language of the document ( **i found that it fails for arabic and chinese**) .
- You can use the `_indexed_chars` to limit the index to a fixed amount of char ( -1 for the full document, 100k default )
## Search

Here are some search examples:

Note the **highlights feature** in the results, and the bad recognition of the chinese language.

![eng-long](https://cloud.githubusercontent.com/assets/6582479/19443662/bf02e3a0-948d-11e6-80d1-18fc6757df48.png)

![stupid-search](https://cloud.githubusercontent.com/assets/6582479/19443671/c5beb192-948d-11e6-9881-c17ae596f734.png)

![chinese-short](https://cloud.githubusercontent.com/assets/6582479/19443677/c9ec4f68-948d-11e6-938e-72074513b2f9.png)
#### **Aggregations:**

![aggs](https://cloud.githubusercontent.com/assets/6582479/19443694/d37f46d4-948d-11e6-9ecb-f8a0b9315add.png)
## Some performance measures

**More tha 300 documents indexed in less than 20 seconds (from 20k to 9M per document):**

![300-docs](https://cloud.githubusercontent.com/assets/6582479/19443697/d914fe54-948d-11e6-8aa8-94dcc67b7b31.png)

**Some measure made with ES Marvel. The first is about the index.**

![index-graph-600-docs](https://cloud.githubusercontent.com/assets/6582479/19443707/dcd6f95c-948d-11e6-9034-823f3cca2779.png)

**The second about the node (the number of documents comprehend even the kibana and marvel data)**

![node-graphs](https://cloud.githubusercontent.com/assets/6582479/19443712/e2db5d2a-948d-11e6-9ea4-f3d8c3a6a362.png)
## Next step:

Figure out how to integrate this feature in invenio

**Comment by jirikuncar** [comment]
Sprint planned for 2016-10-19 09:00. cc @inveniosoftware/developers

**Comment by krzysztof** [comment]
Looks like the work to integrate it is mostly is invenio-records-files: https://github.com/inveniosoftware/invenio-records-files/issues/47
