### ISSUE TITLE
api: bulk indexing two or more times a record

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-indexer#56]
### Problem
Sometimes happen that we add a record inside the bulk queue two o more times in a short period (because e.g. different celery tasks are working with it).
We were wondering if we can/need to optimize the [bulk operation](https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/api.py#L179) from DB side and from ES side. 

### Questions

1. Does `elasticsearch-py` handle automatically this situation?

2. Could we optimize in a way that a record is read from the database no more than one times?

3. Could we maybe use the `Record.get_records()` to improve the read instead of a lot of `Record.get_record()`? 

My [first attempt](https://github.com/hachreak/invenio-indexer/tree/56_bulk_index_improve) to not indexing a record two times.
For sure we can find a better solution, but it can give you an idea to what I mean.

------------------------------------------
cc @egabancho

**Comment by jirikuncar** [comment]
We could compare versions in ES and DB.

**Comment by lnielsen** [comment]
1) The bulk indexer includes the ``_version`` and ``_version_type= external_gte`` which means that a record will be indexed if its version number is greater than or equal to the current version number in ES. I.e. if we first index a new version of a record and then an old version, the old version will simply be discarded from the index. If we index twice the same record version, then ES will also index it twice. If that's not desired the version type can be changed to ``external_gt`` for a specific indexing session.

2) I'm not sure it's worthwhile the effort. As you've correctly tried it's the rabbitmq [message iterator](https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/api.py#L193) which should be changed to not include the same record twice, but often you can have multiple indexing processes running at the same time, so a record added twice in the queue could potentially be indexed from two different worker nodes.

3) Do you have some stats on performance of Record.get_records vs Record.get_record when indexing?

**Comment by lnielsen** [comment]
There is no easy fix for this due to the distributed nature of the indexing. E.g. deduplication has to happen at the queue level and not per worker. The best way to avoid having the same record indexed twice is by not pushing it to the indexer queue twice.
