### ISSUE TITLE
RFC api: zero down-time reindexing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-indexer#62]
**Problem**

Without changing the JSONSchema you may improve the Elasticsearch mapping especially if you say add computed fields. This will require you to create a new index with the new mapping and reindex all records in the new index. 

Right now, you would have to destroy the existing index, recreate it and reindex. This will mean that you search is down (and possibly other parts of Invenio) until the reindexing has finished would could potentially be quite some time causing service disruption.

**Proposal**

Add features to Invenio-Indexer/Search that allows to create a new index together with the current index. Then take a timestamp T1 and query for all records in a given PID namespace that was modified before this timestamp and send them for reindexing. Once they are all reindexed, you take a new timestamp T2 and reindex any record that was modified in the T1-T2 period. You can redo this until there's no changes (or do a maximum number of iterations). Afterwards you change the alias from old index to the new, and your search should now use the new index and mapping without any downtime.

Issues, index names are currently enforced by invenio-search and you cannot rename an index (AFAIK), i.e. you need something like this (which I don't think invenio-search is capable of today).
- records-record-v1.0.0
- records-record-v1.0.0-2

**Comment by kaplun** [comment]
cc: @david-caro, @jmartinm, @jacquerie

**Comment by lnielsen** [comment]
Closing ticket here as first implemantation is available in invenio-index-migrator
