### ISSUE TITLE
App crashes every time Elasticsearch returns an error

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-indexer#88]
Everytime Elasticsearch returns an error (e.g. there is some non-escaped forward slash in the query which is not accepted in out of the box configuration) the return value is not a JSON but a Java Traceback.

In troubleshooting there is a note for these cases: https://github.com/inveniosoftware/troubleshooting/issues/24

Would it be better to treat non-escaped values in the application before sending to Elasticsearch? Or Capture the ``ValueError`` exception and just log it and return error or empty json?

From my point of view the second option is more flexible to allow custom ES configurations.

ES Reserved Characters [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters)

PS: This also applies when searching, therefore I am not sure if it applies more to Invenio-Search or even Invenio-Records-Rest

**Comment by lnielsen** [comment]
Definitely, we should have some more useful errors for the user, so something like your second option where we catch the error.
