### ISSUE TITLE
installation: Redis 3.0 incompatibility; unpin Redis when Kombu releases

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-indexer#95]
Undo https://github.com/inveniosoftware/invenio-indexer/pull/94 when is released https://github.com/celery/kombu/pull/953

**Comment by lnielsen** [comment]
Set to be released in Celery 4.3, thus related to inveniosoftware/invenio-celery#57 and inveniosoftware/cookiecutter-invenio-instance#75 and inveniosoftware/cookiecutter-invenio-instance#75

**Comment by lnielsen** [comment]
celery/celery#5180

**Comment by thedrow** [comment]
Released as Kombu 4.2.2 as it was failing our build and we have to get that passing to release Celery 4.3.

**Comment by lnielsen** [comment]
@thedrow Awesome! Thanks a lot, it's much appreciated!!!

**Comment by ppanero** [comment]
@lnielsen I can actually not fix it cuz is just reseting the head to the previous commit.

```bash
git reset --hard ea6c19d860dfa45a0e3df01d7867bd810a221876
git push -f origin build_fix # master in the inveniosoftware/invenio-indexer case
```

However, I did it in my branch and travis is passing: https://travis-ci.org/ppanero/invenio-indexer/builds/467486110

**Comment by ppanero** [comment]
Fixed in https://github.com/inveniosoftware/invenio-indexer/pull/98
